apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  namespace: nextcloud
data:
  POSTGRES_HOST: nextcloud-postgres:5432
  NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.k88936.top
  APACHE_DISABLE_REWRITE_IP: "1"
  TRUSTED_PROXIES: 10.42.0.0/16
  OBJECTSTORE_S3_BUCKET: "nextcloud"
  OBJECTSTORE_S3_HOST: "rustfs.k88936.top"
  OBJECTSTORE_S3_USEPATH_STYLE: "true"
  OBJECTSTORE_S3_AUTOCREATE: "true"