---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud-k88936-top
  namespace: nextcloud
spec:
  secretName: nextcloud-tls
  dnsNames:
    - nextcloud.k88936.top
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-security-headers
  namespace: nextcloud
spec:
  headers:
    stsSeconds: 15552000
    stsIncludeSubdomains: true
    stsPreload: true
    forceSTSHeader: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-wellknown-redirect
  namespace: nextcloud
spec:
  redirectRegex:
    regex: ^https://([^/]+)/\.well-known/(?:card|cal)dav$
    replacement: https://${1}/remote.php/dav/
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud
  namespace: nextcloud
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: nextcloud-nextcloud-wellknown-redirect@kubernetescrd,nextcloud-nextcloud-security-headers@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - secretName: nextcloud-tls
      hosts:
        - nextcloud.k88936.top
  rules:
    - host: nextcloud.k88936.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud
                port:
                  name: service-port
                